### ISSUE TITLE
Download release zip for GitHub projects 

### ISSUE THREAD

**Issue by TheLartians** [cpm-cmake/CPM.cmake#191]
When the flag `GITHUB_REPOSITORY` is provided together with a version release tag, then GitHub probably has created a zip snapshot. We could likely save bandwidth and storage by downloading that instead of cloning the entire git history.

However, problems could arise if the tag doesn't have an associated release. Maybe CPM.cmake could check first and fallback to a git clone otherwise.

**Comment by iboB** [comment]
Isn't the git clone shallow in such a case anyway? Manually downloading and extracting an archive will likely be slower than a shallow clone, or, at best, just as fast.

**Comment by TheLartians** [comment]
Hm that's a good point as I haven't done any benchmarking. Intuitively, I would have thought that a shallow clone takes more resources but I may be mistaken. This probably requires additional research.

**Comment by iboB** [comment]
A shallow clone is basically a zip download and extract (as is any clone, really). Technically minor other things are done, mostly by the server, but also setup of the `.git` directory in the client. The thing is that for this we never leave git and it does the clone in the fastest way possible. To download and then extract an archive will trigger the shell several (likely two) times, and I expect the delegation to other processes to be the bottleneck of this operation, and essentially trump the minor additional things done by git for the shallow clone.

Still, this is an opinion based on a lot of gut feelings. I'd be glad to see the results of a test.

**Comment by riri** [comment]
@TheLartians 's idea is interesting, but I would see it with a few tweaks, for other usage than getting faster shallow copies.

When having a cross-platform project with dependencies, you might want to allow user to build with dependencies:
- system installed (what find_package does)
- from sources, building the sources (that's how most do with git submodules)
- from a release archive with platform build binaries, (I have seen it's much used for Windows)

What if this could be an option to CPM, like the `DOWNLOAD_ONLY` option?
That would provide per dependency the option to let the user select by default the system package (if available), fallback or force to source url and/or release archive.
Making it an option to the function let the project and project user choose the best in their own case.

Note: I am not a CPM user (yet), I am walking around the project for that and was interested by this topic :)

**Comment by TheLartians** [comment]
Hey @riri, thanks for the input! Tbh I'm not sure I understand completely, as it's not really related to the intent of this issue (speeding up the download), but CPM.cmake already has some [options](https://github.com/cpm-cmake/CPM.cmake#options) that allow users to override library sources for their specific use case, including using the result of `find_packge`, if available.

**Comment by riri** [comment]
Yes you're right, I misused the goal of this issue :)

What I meant was the possibility for the consumer to choose for each dependency how to get or reference it (local install, download from binary archive or download source). From what I understood (local/download source) can be set globally by the options you mentioned, or forcing for one dep is possible with `CPM_<dependency name>_SOURCE`, but it's not possible to specify downloading a prebuilt archive.

Maybe that's beyond the scope of CPM and can be managed by a project related module.

**Comment by riri** [comment]
I just made the test with the GLFW project, manually downloading :
- 3.3.4 release tag archive -> 1.4MB download, 7.4MB extracted (du -hs glfw-3.3.4)
- shallow clone of the 3.3.4 tag -> 5.2MB (du -hs glfw-3.3.4-shallow)

The difference resides in the documentation which is built for the release archive. I couldn't measure the difference in download time, but I suppose @iboB is right, even on bigger project the download time difference might not be that important if the clone is getting a zip.

On a more consequent project (Juce Framework), which has not added files in the release archive, the difference is mostly in the extracted size (because of the .git directory):
- 6.0.8 release tag archvie -> 15.8MB download, 57MB extracted
- shallow clone of the 6.0.8 tag -> 69MB

**Comment by TheLartians** [comment]
> What I meant was the possibility for the consumer to choose for each dependency how to get or reference it (local install, download from binary archive or download source). From what I understood (local/download source) can be set globally by the options you mentioned, or forcing for one dep is possible with CPM_<dependency name>_SOURCE, but it's not possible to specify downloading a prebuilt archive.

Oh gotcha, yeah I don't have experience with prebuilt archives myself. I do think it's difficult to get right as there is a strong system / architecture dependency, so it's probably best to leave this to the system package managers in combination with `CPM_USE_LOCAL_PACKAGES`. Perhaps we could also add a more granular control for individual dependencies, such as `CPM_USE_LOCAL_<dependency name>`.

> Download time difference was not noticeable.

Thanks for doing the testing, that should resolve this issue then. If you want to further discuss functions related to prebuilt archives, feel free to open a new issue!
