### ISSUE TITLE
Unknown CMake command "CPMAddPackage"

### ISSUE THREAD

**Issue by NicholasBertazzon** [cpm-cmake/CPM.cmake#199]
Hi,
I'm facing this problem when reloading the CMake configuration on CLion.

`Unknown CMake command "CPMAddPackage"`

The problem disappears if I remove the checks that starts with `if(CPM_DIRECTORY)` in the CPM.cmake.
What I can tell you is that it comes from the CMakeCache.txt, there's probably a cached option that is preventing your script from going on and declare the functions needed.

Tried with both the bundled CMake 3.17 that the latest CMake binaries (3.19+).

**Comment by Andres6936** [comment]
Do you have the steps to reproduce the problem?, I am also a CLion user and have not experienced this problem.

**Comment by NicholasBertazzon** [comment]
@Andres6936 it was just a fresh hello world project, I added CPM and then RocksDB through CPMAddPackage.
First run is fine, it gets downloaded and all, then at the second run the problem appears.
I am on the latest Win 10, latest CMake and latest Clion.

This evening I will debug it further and get the actual cached variable that's giving me the error

**Comment by TheLartians** [comment]
I believe this might occur if you change the directory where the current CPM.cmake script is located without removing `CPM_DIRECTORY` cache variable from the CMake cache. This tricks CPM.cmake to believe that it has already been included from a different location and immediately returns without defining its functions. Have you tried clearing the build directory or removing the cache variable `CPM_DIRECTORY`?

**Comment by NicholasBertazzon** [comment]
@TheLartians yes, `CPM_DIRECTORY:INTERNAL=../../../../Downloads`

Found out why, I already tried removing the build dir and all, what I found is that `${CMAKE_CURRENT_LIST_DIR}` on the CPM.cmake has become 
```
set(CPM_DIRECTORY
        ../../../../Downloads
    CACHE INTERNAL ""
)
```

I don't know how, I didn't do that.

**Comment by NicholasBertazzon** [comment]
@TheLartians solved by replacing the content of CPM.cmake with a copy of the raw CPM.cmake from the repo directly. Who know what CLion does to the file when put into the editor.

Thanks :)

**Comment by TheLartians** [comment]
@NicholasBertazzon interesting, haven't heard of that before. Glad you could resolve the issue!

**Comment by adamski** [comment]
I am getting this issue on trying out CPM for an existing project. 

```
include(../cmake/CPM.cmake)
CPMAddPackage(
        JUCE
        GIT_REPOSITORY https://github.com/tracktion/JUCE.git
        GIT_TAG tracktion/develop
)
```

I've confirmed the correct location of CPM.cmake.

I tried replacing it with the raw file from the GitHub tag release. 

Anything else I can try?

**Comment by adamski** [comment]
Could it be to do with having FetchContent used/included in other parts of the project?

**Comment by TheLartians** [comment]
@adamski have you tried clearing the CMake cache / build directory?

**Comment by adamski** [comment]
Yes. I tried again and got past that error but now, I get this: 

```
-- CPM: adding package JUCE@ (tracktion/develop at /Users/adamwilson/.cache/CPM/juce/ee624fdaa67a383852eed29bb4dd5d40a003dc09)
CMake Error at Source/CMakeLists.txt:12 (juce_set_vst2_sdk_path):
  Unknown CMake command "juce_set_vst2_sdk_path".
```

**Comment by TheLartians** [comment]
Not really sure, as it seems to be a library problem, but try changing the command to set the name properly and use a git commit or tag as `GIT_TAG` argument. Using branch names isn't recommended or supported as the library version you get may be unexpected. 

```diff
   CPMAddPackage(
---        JUCE
+++        NAME JUICE
           GIT_REPOSITORY https://github.com/tracktion/JUCE.git
---        GIT_TAG tracktion/develop
+++        GIT_TAG 087cda7e1f359855889e28dbf69b3767f21e9f08
   )
```

**Comment by TheLartians** [comment]
That's weird, the following standalone CMake script works for me. Can you run it?

```cmake
cmake_minimum_required(VERSION 3.14 FATAL_ERROR)

project(Playground LANGUAGES CXX)

set(CPM_DOWNLOAD_VERSION 0.32.0) 
set(CPM_DOWNLOAD_LOCATION "${CMAKE_BINARY_DIR}/cmake/CPM_${CPM_DOWNLOAD_VERSION}.cmake")
if(NOT (EXISTS ${CPM_DOWNLOAD_LOCATION}))
  message(STATUS "Downloading CPM.cmake v${CPM_DOWNLOAD_VERSION}")
  file(DOWNLOAD https://github.com/cpm-cmake/CPM.cmake/releases/download/v${CPM_DOWNLOAD_VERSION}/CPM.cmake ${CPM_DOWNLOAD_LOCATION})
endif()
include(${CPM_DOWNLOAD_LOCATION})

CPMAddPackage(
    NAME JUCE
    GIT_REPOSITORY https://github.com/tracktion/JUCE.git
    GIT_TAG 871a4130e5f7cdf59ffd3d39167081b086c10a06
)

juce_set_vst2_sdk_path("")
```

**Comment by adamski** [comment]
That works for me too!
