### ISSUE TITLE
Auto-formatting comments

### ISSUE THREAD

**Issue by iboB** [cpm-cmake/CPM.cmake#214]
While auto-formatting code is great (well... in most cases) I personally am against auto-formatting comments. Comments are literature in a way and the style the author has chosen is important.

We may want to ascii art to a comment

```cmake
#   _____ _____  __  __ 
#  / ____|  __ \|  \/  |
# | |    | |__) | \  / |
# | |    |  ___/| |\/| |
# | |____| |    | |  | |
#  \_____|_|    |_|  |_|
#
```

But more importantly sometimes having a short sentence and a new line for an emphasized clarification or note is also important:

```cmake
# This function does this and that
# Note that if arg1 greater than 32, your computer may explode
```

Not to mention that autoformatting commented-out code is kinda silly. For example see the extra new lines to prevent that in the commented out tests in #207 

I think the auto-formatter should just ignore comments altogether

**Comment by TheLartians** [comment]
Tbh I do like the auto-wrapping of long comment lines as it makes the overall code more consistent and easier to read in GitHub. In cases where auto-formatting does not work properly we can simply use [`# cmake-format: off`](https://github.com/cheshirekow/cmake_format#disable-formatting-locally) to turn off formatting locally. This will also make it more clear to maintainers that a specific formatting choice is intentional.

**Comment by iboB** [comment]
While I can accept auto-wrapping at times (while I still think it's bad for commented-out code), but auto-unwrapping is a pain. Imagine the case in a long text comment where one formats the first line, deleting a word or replacing it with a shorter one. Then the diff for this commit will be 20 lines of reformatted text.

Adding `# cmake-format: off` on every other line can be annoying, especially when reading code.

Is it possible to make the auto-formatter only issue warnings instead of errors for comments and leave it to the author to choose whether to do something about them?

**Comment by iboB** [comment]
Another use case I hit recently:

I want to comment on what's being checked in different `elseif` clauses. I would format the code like this:

```cmake
  if(foo)
    code()
    
  # Check if we can still do something with the data
  elseif(a somewhat complicated condition)
  endif()
```

But the auto-formatter insists on adding indentation to my comment about the `elseif` as if it's for the code inside the `if` block

**Comment by TheLartians** [comment]
> While I can accept auto-wrapping at times (while I still think it's bad for commented-out code), but auto-unwrapping is a pain. Especially for code. But also imagine the case in a long text comment where one formats the first line, deleting a word or replacing it with a shorter one. Then the diff for this commit will be 20 lines of reformatted text.

Yeah I see the issue with long commits for small changes, but for me properly wrapped code is way more readable than multiple lines of different length. Note that if you want to intentionally split lines, you could just use an empty comment to create a paragraph. 

```
# This is a paragraph
#
# This is a second paragraph
#
# This is a third paragraph
``` 

> Adding # cmake-format: off on every other line can be annoying, especially when reading code.

Would it really be that common though? The formatting stays off until the end of the file or `# cmake-format: on` is encountered, so for example in #207, this would only be a single change:

```diff
# The following test cases are to be used in the future, once single-argument archives are supported
+ # cmake-format: off
[anything remaining remains unformatted] 
```

> Is it possible to make the auto-formatter only issue warnings instead of errors for comments and leave it to the author to choose whether to do something about them?

I don't think so unfortunately. Also as a PR reviewer there would be no way to know if the warning was triggered or if the code is properly formatted.

> I want to comment on what's being checked in different elseif clauses. I would format the code like this:

This is all personal taste ofc, but I would actually expect the code to be inside the condition code.

```cmake
  if(foo)
    code()
  elseif(
    # Check if we can still do something with the data
    a somewhat complicated condition
  )
    more()
    code()
  endif()
```

**Comment by iboB** [comment]
Ok. I'll try to work around the comment limitations 
I'm still sad, though 😢

**Comment by TheLartians** [comment]
I agree that it takes some getting used to, but strict code formatting has made my life so much easier. Sorry for being religious about this. 😅 

Anyways, if you find some cmake-format configuration that works better overall (besides turning off the formatting for comments), feel free to suggest changes! :)
