### ISSUE TITLE
[Question] Can this be safely used in a Find<ModuleName>.cmake?

### ISSUE THREAD

**Issue by Neumann-A** [cpm-cmake/CPM.cmake#229]
The idea is to write/supply a `Find<ModuleName>.cmake` which always succeeds by either finding the requested module or downloading and building it. This way CPM could be injected in existing cmake builds without requiring changes to an existing  `CMakeLists.txt`.

**Comment by TheLartians** [comment]
If I understand correctly, this feature is already supported. During configuration, CPM.cmake creates a directory in `build/CPM_modules` that is [added](https://github.com/cpm-cmake/CPM.cmake/blob/8afc2af4f9a8c00b6b3397c6d4e1b58804e16133/cmake/CPM.cmake#L121) to the CMake modules path. This directory contains a `Find<dependency-name>.cmake` files for each dependency. This allows us to inject CPM.camke dependencies into other projects non-intrusively.

**Comment by TheLartians** [comment]
From the CMake Slack conversation:

> Is there any reason to not have it in a `Find<Module>.cmake`?

The main reason to use CMake directly is convenience, as I see the CMakeLists.txt as a project manifest that should be mostly or less [self-contained](https://github.com/TheLartians/ModernCppStarter/blob/master/CMakeLists.txt) (a json based format would be even better 😉).  But you could definitely use CPM.cmake in your own `find_package` modules as well if you want a clean separation.
