### ISSUE TITLE
Specify a source subdirectory

### ISSUE THREAD

**Issue by bilke** [cpm-cmake/CPM.cmake#237]
Some libraries have their root-CMakeLists.txt in a subdirectory of their source tree (e.g. `./src`). It would be really helpful if CPM would allow for specifying this subdirectory. Current behavior is that CPM does not include the CMake project because there is no CMakeLists.txt at the project root.

I noticed that `FetchContent_MakeAvailable()` [provides the option `SOURCE_SUBDIR`](https://cmake.org/cmake/help/latest/module/FetchContent.html#command:fetchcontent_makeavailable) but I noticed that CPM does not call `FetchContent_MakeAvailable()`.

**Comment by TheLartians** [comment]
Interesting, I wasn't aware of the `SOURCE_SUBDIR` feature of `FetchContent`. I can see how it would be a useful feature!

**Comment by johelegp** [comment]
Does it not work with `OPTIONS`? I'm pretty sure I've used it before.

**Comment by TheLartians** [comment]
Come to think of it this should have been possible before, but has been broken due to bypassing `FetchContent` in #182.

**Comment by TheLartians** [comment]
Fixed in `v0.31.2`! 🎉
