### ISSUE TITLE
Shorthand syntax doesn't setup a dependency for linking

### ISSUE THREAD

**Issue by mscofield0** [cpm-cmake/CPM.cmake#245]
Using `fmt` as an example, `CPMAddPackage("gh:fmtlib/fmt#7.1.3")` doesn't setup `fmt` to be linked for some reason.

Linking with:
```cmake
target_link_libraries(Greeter PRIVATE fmt::fmt)
```

The error is:
```
...
[cmake] -- CPM: adding package fmt@7.1.3 (7.1.3)
[cmake] -- Version: 7.1.3
[cmake] -- Build type: Debug
[cmake] -- CXX_STANDARD: 11
[cmake] -- Required features: cxx_variadic_templates
[cmake] -- CPM: adding package Format.cmake@1.7.0 (v1.7.0)
[cmake] -- Configuring done
[cmake] CMake Error: install(EXPORT "GreeterTargets" ...) includes target "Greeter" which requires target "fmt" that is not in any export set.
[cmake] -- Generating done
[cmake] CMake Generate step failed.  Build files cannot be regenerated correctly.
```

Tested with `spdlog` too (`CPMAddPackage("gh:gabime/spdlog@1.8.5")`), same error:

```
...
[cmake] CMake Error: install(EXPORT "GreeterTargets" ...) includes target "Greeter" which requires target "spdlog" that is not in any export set.
...
```

Maybe I'm missing something?

**Comment by mscofield0** [comment]
I will also add it doesn't work with linking it this way either:
```cmake
target_link_libraries(Greeter PRIVATE fmt::fmt)
```
I am given the same error as in the original post.

**Comment by TheLartians** [comment]
The issue is that CMake cannot create an **installable** target for "Greeter", as fmt is not configured for installation by default. For installation, you need to set the option `FMT_INSTALL` to yes, either by defining it externally or passing it to CPM:

```cmake
CPMAddPackage(
  NAME fmt
  GIT_TAG 7.1.3
  GITHUB_REPOSITORY fmtlib/fmt
  # create an installable target
  OPTIONS "FMT_INSTALL YES"
)
```

**Comment by mscofield0** [comment]
Sorry for the maybe dumb question, but how else would you use `fmt` with the shorthand syntax? How do you make it work?

**Comment by TheLartians** [comment]
Unfortunately, shorthand syntax only rally works for CMake projects that are properly configured for package usage **by default**. Otherwise we always need to pass parameters for proper configuration. On alternative would be to define the option externally before adding the package, e.g.

```cmake
set(FMT_INSTALL YES)
CPMAddPackage("gh:fmtlib/fmt#7.1.3")
```

But I can't really recommend this approach, as the option leaks into the outer scope and the association to the dependency isn't clear.

**Comment by mscofield0** [comment]
Thanks for the quick responses. I will close this now.
