### ISSUE TITLE
Question: How does `CPMFindPackage()` find the local dependency with only the typical specified information 

### ISSUE THREAD

**Issue by mscofield0** [cpm-cmake/CPM.cmake#246]
I need to document and explain the entire ModernCppStarter ecosystem for my organization and I don't understand how it finds it with, for example, `GITHUB_REPOSITORY`. 

Could you please explain it a bit further?

**Comment by TheLartians** [comment]
In essence `CPMFindPackage(NAME <name> VERSION <version> <Other Args>)` tries to call [`find_package(<name> <version>)`](https://cmake.org/cmake/help/latest/command/find_package.html). If the package isn't found (`<name>_FOUND` isn't truthy afterwards), it forwards all arguments to `CPMAddPackge(NAME <name> VERSION <version> <Other Args>)`.

Note though that I actually don't recommend using `CPMFindPackage`, but rather only endorse `CPMAddPackage`, as the behaviour is more predictable and reproducible between different systems.

Does this answer your question?

**Comment by mscofield0** [comment]
Ah so it's `find_package()` doing the magic behind the scenes, not `CPMFindPackage()`. Yes, that answers my question. Thanks.
