### ISSUE TITLE
Question: About `<dependency>_ADDED`

### ISSUE THREAD

**Issue by mscofield0** [cpm-cmake/CPM.cmake#247]
Is the following a mistake?
> `<dependency>_ADDED` is set to `YES` if the dependency has not been added before, **otherwise it is set to `NO`**.

Why would it be set to `NO` if the dependency was added before?

**Comment by TheLartians** [comment]
Often we need to setup some configuration **only if** the dependency has just been added, but not if it's already been added before. For example with Lua we need to setup the targets ourselves:

```cmake
CPMAddPackage(
  NAME lua
  GIT_REPOSITORY https://github.com/lua/lua.git
  VERSION 5.3.5
  DOWNLOAD_ONLY YES
)

if (lua_ADDED)
  # lua has no CMake support, so we create our own target

  FILE(GLOB lua_sources ${lua_SOURCE_DIR}/*.c)
  list(REMOVE_ITEM lua_sources "${lua_SOURCE_DIR}/lua.c" "${lua_SOURCE_DIR}/luac.c")
  add_library(lua STATIC ${lua_sources})

  target_include_directories(lua
    PUBLIC
      $<BUILD_INTERFACE:${lua_SOURCE_DIR}>
  )
endif()
```

This would error if a target named Lua has already been added before, e.g. by another dependency or package upstream, that would use a similar process to initialise the targets.

**Comment by mscofield0** [comment]
Ah, makes sense now. Thanks again.
