### ISSUE TITLE
Example for a project using a package lock file

### ISSUE THREAD

**Issue by mscofield0** [cpm-cmake/CPM.cmake#248]
Hello again, I don't see an example of a project using a package lock file on the repo. Looking through some of the issues, I see that the API for adding packages is also different than usual. I don't see where to go from here, and it might be troubling for other newcomers as well.

Could you add some example/s where a package lock is used in a project?

**Comment by TheLartians** [comment]
Hey, so the package lock essentially allows to manage dependencies from a single file in large projects, without needing to change other CMake files. You can see an example usage in my [modern-wasm-starter](https://github.com/TheLartians/modern-wasm-starter/blob/master/wasm/package-lock.cmake) project.

Note that it's more of an advanced feature and not suited for library projects. If you don't already see the need for it, I'd recommend against using it in your projects.

**Comment by mscofield0** [comment]
Ah, thanks for the link to the example project. I still think it would be worth putting some example usage in the readme or wiki though. 

Anyways, thanks again, I'll close this now.
