### ISSUE TITLE
Trouble linking crossplatform library 🙏

### ISSUE THREAD

**Issue by developer239** [cpm-cmake/CPM.cmake#249]
**Full reproduction:** https://github.com/developer239/test_cpm
**Repository that I can't link:** https://github.com/smasherprog/screen_capture_lite 

```
# CMAkeList.txt

cmake_minimum_required(VERSION 3.19)
project(test_cpm)

set(CMAKE_CXX_STANDARD 14)

# CPM
set(CPM_DOWNLOAD_VERSION 0.27.2)
set(CPM_DOWNLOAD_LOCATION "${CMAKE_BINARY_DIR}/cmake/CPM_${CPM_DOWNLOAD_VERSION}.cmake")

if(NOT (EXISTS ${CPM_DOWNLOAD_LOCATION}))
    message(STATUS "Downloading CPM.cmake")
    file(DOWNLOAD https://github.com/TheLartians/CPM.cmake/releases/download/v${CPM_DOWNLOAD_VERSION}/CPM.cmake ${CPM_DOWNLOAD_LOCATION})
endif()

include(${CPM_DOWNLOAD_LOCATION})

# EXECUTABLES

add_executable(test_cpm main.cpp)

# DEPENDENCIES

CPMAddPackage(NAME spdlog GITHUB_REPOSITORY gabime/spdlog VERSION 1.7.0)

CPMAddPackage(
        NAME Screen_Capture
        GITHUB_REPOSITORY smasherprog/screen_capture_lite
        GIT_TAG 17.0.3
)

target_link_libraries(test_cpm spdlog Screen_Capture)
```

```
# main.cpp

#include <spdlog/spdlog.h>
#include <Screen_Capture.h>

int main() {
    spdlog::info("Hello world!");
    return 0;
}
```

**Log:**

Maybe I misunderstood how does the linking work? 🤔  I had very similar problem with `opencv`.

```
fatal error: 'Screen_Capture.h' file not found
#include <Screen_Capture.h>
```

![image](https://user-images.githubusercontent.com/14946081/115974179-413c2600-a55b-11eb-9d5b-21742fd99297.png)

**Comment by Andres6936** [comment]
Change this code line: 

```cmake
target_link_libraries(test_cpm spdlog Screen_Capture)
```

 to 

```cmake
target_link_libraries(test_cpm spdlog screen_capture_lite)
```

**Comment by developer239** [comment]
@Andres6936 I already tried most of the combinations but none of them worked. 🙁 

Here is the commit: https://github.com/developer239/test_cpm/commit/7bb41f9816d52688f5354c6517d1264a5a480c7e

![image](https://user-images.githubusercontent.com/14946081/115991948-581a6100-a5cb-11eb-8d51-51e4a1345d2a.png)

**Comment by Andres6936** [comment]
One of the problems you have is trying to use a repository with a bad CMake support, that is the root of the problem you have, with the previous comment you have already solved the problem of the undefined references, now you have the problem of locating the headers that your project needs.
I also had the same problem with libgit2, the way to solve it is to include the path where those headers are located, how, I explain with the example:

Look at the CMake of this [repository](https://github.com/Andres6936/Gt/blob/master/CMakeLists.txt), and the structure of the [libgit2](https://github.com/libgit2/libgit2) project.

As I mentioned in the Wiki of this project, the correct project structure is not followed to the letter by libgit2, hence I must maneuver the problem with CMake, how? Simple, telling CMake and therefore CLion where to locate the headers (in this particular case is the main header, but applies to any other case).

**Comment by Andres6936** [comment]
Para tu caso, el CMake de tu proyecto debe de verse así:

```cmake
cmake_minimum_required(VERSION 3.19)
project(test_cpm)

set(CMAKE_CXX_STANDARD 14)

# CPM
set(CPM_DOWNLOAD_VERSION 0.27.2)
set(CPM_DOWNLOAD_LOCATION "${CMAKE_BINARY_DIR}/cmake/CPM_${CPM_DOWNLOAD_VERSION}.cmake")

if(NOT (EXISTS ${CPM_DOWNLOAD_LOCATION}))
    message(STATUS "Downloading CPM.cmake")
    file(DOWNLOAD https://github.com/TheLartians/CPM.cmake/releases/download/v${CPM_DOWNLOAD_VERSION}/CPM.cmake ${CPM_DOWNLOAD_LOCATION})
endif()

include(${CPM_DOWNLOAD_LOCATION})

# EXECUTABLES

add_executable(test_cpm main.cpp)

# DEPENDENCIES

CPMAddPackage(NAME spdlog GITHUB_REPOSITORY gabime/spdlog VERSION 1.7.0)

CPMAddPackage(
        NAME SCREEN_CAPTURE
        GITHUB_REPOSITORY smasherprog/screen_capture_lite
        GIT_TAG 17.0.3
)

target_include_directories(test_cpm ${SCREEN_CAPTURE_SOURCE_DIR}/include/)
target_link_libraries(test_cpm spdlog screen_capture_lite)
```

**Comment by Andres6936** [comment]
@TheLartians I consider it prudent to close the incident, based on the inactivity of @developer239

**Comment by developer239** [comment]
@Andres6936 I appreciate the time you took to answer my question and I will take a look at it again later this week. Changes you proposed didn't fix the problem but I guess we can close this issue because it is not related to `CPM` directly.

**Comment by Andres6936** [comment]
Thanks to you, we are here to help you.

**Comment by developer239** [comment]
@Andres6936 I couldn't make it work so first I will create MacOs only library myself. 🙌 Thank you for your time though I will definitely use CPM/CMake in the project though.

**Comment by developer239** [comment]
@Andres6936 I closed the issue 2 days ago but I just wante to share with you that I didn't make the CPM work with that repository so I wrote mouse/keyboard and screen control myself. Maybe it was a good thing. 😅

**Comment by Andres6936** [comment]
You are right, `brew` can simplify a lot the dependency process with OpenCV, you don't need CPM in this case, on the other hand, a good starting point is to structure your project, I had already written it in the [Wiki](https://github.com/cpm-cmake/CPM.cmake/wiki/Preparing-projects-for-CPM.cmake), and there is even a basic [template](https://github.com/TheLartians/ModernCppStarter) with the necessary structure, once you complete this step we will continue with the other one.
