### ISSUE TITLE
[Feature request] Armadillo example

### ISSUE THREAD

**Issue by smrfeld** [cpm-cmake/CPM.cmake#257]
Can you add to the examples the [armadillo](http://arma.sourceforge.net) linear algebra library?
It is hosted through sourceforge, not github.

Thanks

**Comment by Andres6936** [comment]
Apparently the project is hosted on Gitlab, CPM currently has support for Github and Gitlab. If you want to use Armadillo, you can use the following code snippet, note that since the project does not have any published releases, you must choose a hash of the commit you want to use. 

```cmake
CPMAddPackage("gl:conradsnicta/armadillo-code#483fee2b46751afa03306bb68a0a6a67e2ea9166")
```

###### Disclaimer: The previous code snippet has not been tested.

**Comment by smrfeld** [comment]
Thanks! Since they didn't have tags for some reason, I avoided their GitLab in favor of the releases on SourceForge, but I didn't know about the commit feature

**Comment by TheLartians** [comment]
@smrfeld is the issue still relevant?

**Comment by smrfeld** [comment]
@TheLartians Yes I was happy with the solution:
```
CPMAddPackage(
	URL "https://sourceforge.net/projects/arma/files/armadillo-10.5.1.tar.xz"
	NAME armadillo
	VERSION 10.5.1
	)
```
Thanks

**Comment by ElektrikAkar** [comment]
> @TheLartians Yes I was happy with the solution:
> 
> ```
> CPMAddPackage(
> 	URL "https://sourceforge.net/projects/arma/files/armadillo-10.5.1.tar.xz"
> 	NAME armadillo
> 	VERSION 10.5.1
> 	)
> ```
> 
> Thanks

Hi I was also using this solution but recently on Github Actions I started to receive [this SSL problem](https://hastebin.com/share/itumulamiv.csharp). 

Therefore, currently I have switched to the following code in case anybody needs an alternative:
```cmake
  CPMAddPackage(
    NAME armadillo
    URL "https://gitlab.com/conradsnicta/armadillo-code/-/archive/12.6.x/armadillo-code-12.6.x.tar.gz"
    OPTIONS
    "BUILD_SMOKE_TEST OFF"
  )
```
