### ISSUE TITLE
CPMAddPackage: Parameter EXCLUDE_FROM_ALL has no effect when Local package override is given on the cmdline

### ISSUE THREAD

**Issue by emweber** [cpm-cmake/CPM.cmake#260]
After adding the command `message(WARNING "CPMAddPackage=${ARGN}")` I get the following stacktrace:

CMake Warning at cmake/CPM.cmake:356 (message):
  
  CPMAddPackage=NAME;fls;GIT_REPOSITORY;ssh://gerrit.intra.razorcat.com:29418/develop/fls.source;GIT_TAG;master;EXCLUDE_FROM_ALL;YES
Call Stack (most recent call first):
  library/CMakeLists.txt:9 (CPMAddPackage)

CMake Warning at cmake/CPM.cmake:356 (message):
  
  CPMAddPackage=NAME;fls;SOURCE_DIR;/home/m.weber/devel/fls.source/Source;FORCE;True;OPTIONS
Call Stack (most recent call first):
  cmake/CPM.cmake:469 (CPMAddPackage)
  library/CMakeLists.txt:9 (CPMAddPackage)

As you can see, the `EXCLUDE_FROM_ALL;YES` is missing in the final call of CPMAddPackage.

**Comment by TheLartians** [comment]
Thanks for opening the issue, seems we forgot about package overrides when adding the exclude option!
