### ISSUE TITLE
Clion shows packages located in cache as hashes. There should be names

### ISSUE THREAD

**Issue by pgorgon-hem** [cpm-cmake/CPM.cmake#266]
![image](https://user-images.githubusercontent.com/35261470/121159687-b0d84d00-c84b-11eb-91c2-870ebea75ca6.png)
I can propose quick fix in directories naming scheme, ie. add directory with package name inside hash-named directory. The problem is that it brakes current cache structure. I have 2 solutions: additional variable which enables this feature or detection of old cache and use it, copy to the new one or remove and populate again. What do you think?

**Comment by pgorgon-hem** [comment]
Example of my solution: 
![image](https://user-images.githubusercontent.com/35261470/121160779-abc7cd80-c84c-11eb-8a3b-928fb4851112.png) 
and in code:
![image](https://user-images.githubusercontent.com/35261470/121160856-beda9d80-c84c-11eb-8c9c-50debf75eb30.png)

**Comment by iboB** [comment]
I am generally NOT in favor of this for backwards compatibility reasons though it could work with this workaround.

I wonder whether we can request a CLion feature to somehow the name of such directories. It will also work with FetchContent-based projects which don't use CPM

**Comment by pgorgon-hem** [comment]
It also sounds good, but I will make PR, you can look into code. I tried a few options and I think that movement of old cache directories to new location looks the best.

**Comment by TheLartians** [comment]
Feature added in #268.
