### ISSUE TITLE
Detecting when the cache is dirty

### ISSUE THREAD

**Issue by apGribble** [cpm-cmake/CPM.cmake#274]
Provide a warning during configuration if the cache has been modified.
Ideally the checks would include:
- Is the working directory for the cache clean.
- Is the repository still checked out at the correct version/commit

### Discussed in https://github.com/cpm-cmake/CPM.cmake/discussions/273

<div type='discussions-op-text'>

<sup>Originally posted by **apGribble** June 23, 2021</sup>
When using the CPM_SOURCE_CACHE option is there a way to raise a warning or error during the configure process if the cache has been modified since being checked out.

Intellisense makes it particularly easy to inadvertently end up modifying one of the source files in the cache that will effect all builds on that machine that use the associated library.
 </div>

**Comment by apGribble** [comment]
@TheLartians I've had a first go at creating a version that detects if the working directories in the cache are clean [link](https://github.com/apGribble/CPM.cmake/commit/dc5561e503373ff144858ec147b62f3a09c6632c#diff-6fcfee7f313f15253f88285a499e62cb58746d47ff2cfec173f1f4cd29feb44d). I'm a bit concerned about how long the git status commands will take given the effort you have gone to remove the delays from calling FetchContent on a local directory. Do you have a standard way of testing the performance?

**Comment by TheLartians** [comment]
Hey @apGribble, looks good imo, feel free to open a PR if you want to discuss this feature further!

> I'm a bit concerned about how long the git status commands will take given the effort you have gone to remove the delays from calling FetchContent on a local directory. Do you have a standard way of testing the performance?

Good thinking! I think @iboB has set up a simple benchmark some time ago, but we don't have a standard one setup atm. As for the delay, the main problem with FetchContent is that it seems to create and configure an additional full CMake project per dependency, resulting in up to 1s delays each. So I believe simply calling a git command should not be too problematic, but at this point it may be worth setting up a benchmark project.

**Comment by andijcr** [comment]
I was looking for something like this, since i'm prone to forgetting that I'm modifying the cache lib.
I removed the FATAL_ERROR to be able to handle non-git folders, here's the [pull request](https://github.com/apGribble/CPM.cmake/pull/1/files )
I didn't add a real check, maybe it's possible to use a fallback method

**Comment by TheLartians** [comment]
Implemented in #284.

**Comment by TheLartians** [comment]
Feature is released in `v0.33.0` 🎉
