### ISSUE TITLE
download library from a specific branch

### ISSUE THREAD

**Issue by x0rld** [cpm-cmake/CPM.cmake#282]
Is it possible to specify a branch to download another branch than main/master ?

**Comment by TheLartians** [comment]
Yes, you can theoretically specify any branch you want. Note however that it is not recommended, as the versioning behaviour will be unexpected and your builds can become unreproducible. Better would be to specify a commit hash or tag, which can also be located in an any git branch.

**Comment by x0rld** [comment]
thank you
