### ISSUE TITLE
cpm_fetch_package might populate an already populated target

### ISSUE THREAD

**Issue by OlivierLDff** [cpm-cmake/CPM.cmake#287]
`cpm_fetch_package` test `${lower_case_name}_POPULATED`, but `string(TOLOWER "${PACKAGE}" lower_case_name)` is called after :

https://github.com/cpm-cmake/CPM.cmake/blob/c5cb85b2f1eae7e23fdb33bb2892d034a0e46404/cmake/CPM.cmake#L759-L765

Bug introduced by : 32b063eba5c754f833725ed4b9e5f352bc3ca959

I'm working on a PR with a unit test covering this case.

I have this issue, when a dependency fetched some content with traditional FetchContent_Declare/FetchContent_MakeAvailable
And then another project tries to fetch the same dependency with `CPMAddPackage`

**Comment by TheLartians** [comment]
Outch, thanks for finding the issue. Looking forward to the PR!

**Comment by OlivierLDff** [comment]
Found it by replacing FetchContent with CPM in projects. So I have mix FetchContent/CPMAddPackage.

I now have a second issue after the fix:
`cpm_add_subdirectory` is always called, no matter if content has been populated or not.
https://github.com/cpm-cmake/CPM.cmake/blob/c5cb85b2f1eae7e23fdb33bb2892d034a0e46404/cmake/CPM.cmake#L590-L595

I get (I'm doing the unit using the fibonnaci example, I called the dependency `Fibonnaci`, to be sure that lower case and upper case variable are different):

```
CMake Error at C:/Users/olivi/Documents/dev/CPM.cmake/cmake/CPM.cmake:748 (add_subdirectory):
  The binary directory

    C:/Users/olivi/Documents/dev/CPM.cmake/build/test/fetchcontent_dependency/_deps/fibonacci-build

  is already used to build a source directory.  It cannot be used to build
  source directory

    C:/Users/olivi/Documents/dev/CPM.cmake/build/test/fetchcontent_dependency/_deps/fibonacci-src

  Specify a unique binary directory name.
Call Stack (most recent call first):
  C:/Users/olivi/Documents/dev/CPM.cmake/cmake/CPM.cmake:593 (cpm_add_subdirectory)
  CMakeLists.txt:24 (CPMAddPackage)
```

Is there a reason for that? What I am missing here?
I think cpm_fetch_package should return some value to say if `cpm_add_subdirectory` should happen.

**Comment by TheLartians** [comment]
> Is there a reason for that? What I am missing here?

Yeah, it's probably that we didn't have we have interoperability checks for "naked" FetchContent with CPM.cmake, so we didn't run into the situation until now.

> I think cpm_fetch_package should return some value to say if `cpm_add_subdirectory` should happen.

I agree, we can probably assume that a source directory has been added if it's been externally populated by FetchContent.
