### ISSUE TITLE
It's not possible to pass list as option

### ISSUE THREAD

**Issue by flagarde** [cpm-cmake/CPM.cmake#291]
hi,
Thx for this nice tool :)
I try to pass some list in option like this 

```cmake
 CPMAddPackage(NAME ROOT
               GIT_REPOSITORY ${ROOT_REPOSITORY}
               GIT_TAG ${ROOT_TAG}
               FETCHCONTENT_UPDATES_DISCONNECTED ${IS_OFFLINE}
               OPTIONS "ROOT_BUILTINS ZLIB;OpenSSL")
```

but it seems not possible. I'm wrong?
If it's not possible; one easy workaround would be to pass it as `ROOT_BUILTINS ZLIB|OpenSSL` and then use `string(REPLACE "\;" ";" OPTION_VALUE ${OPTION_VALUE})`  in  `cpm_parse_option`

**Comment by TheLartians** [comment]
Good question, I'm not sure if it works, but have you tried to set the option by escaping the semicolon? e.g. using `"ROOT_BUILTINS ZLIB\;OpenSSL"` or `"ROOT_BUILTINS ZLIB\\\;OpenSSL"` (I'm not sure if we need multiple escapes).

> one easy workaround would be to pass it as `ROOT_BUILTINS ZLIB|OpenSSL` and then use `string(REPLACE "\;" ";" OPTION_VALUE ${OPTION_VALUE})` in `cpm_parse_option`

Do you mean replacing `|` with `;` in the options? That would then raise the question on how to pass `|` though...

**Comment by flagarde** [comment]
Hi, 

Itried `"ROOT_BUILTINS ZLIB\;OpenSSL"` I will try the other one.

Yes it could be replaced in the options. Sure but I don't think `|` is used so much in options

**Comment by amirmasoudabdol** [comment]
I have tried several combinations, with and without `\;`, `\\\;`, `\"ITEM;ITEM\"`, `\"ITEM\;ITEM\"`, and several more and I couldn't get it to work either.
