### ISSUE TITLE
How to integrate the nanopb library?

### ISSUE THREAD

**Issue by CodeFinder2** [cpm-cmake/CPM.cmake#294]
HI,

I am trying to switch to CPM and really like it so far!

I am now trying to integrate the [nanopb library](https://github.com/nanopb/nanopb):

```cmake
# ...
include(cmake/CPM.cmake)
CPMAddPackage("gh:nanopb/nanopb#0.4.5")

NANOPB_GENERATE_CPP(PROTO_SRCS PROTO_HDRS protoc/example.proto) # line 19

add_library(${PROJECT_NAME} STATIC ${PROTO_SRCS} ${PROTO_HDRS})
target_include_directories(${PROJECT_NAME} PUBLIC ${NANOPB_INCLUDE_DIRS} ${CMAKE_CURRENT_BINARY_DIR} include)
```

I've been using that library as a git submodule previously so it should support being added as a CMake subdirectory nicely. However, the problem is that  `NANOPB_GENERATE_CPP()` is not found. Do you have an idea on how to integrate this properly?

(The function is defined in `FindNanopb.cmake` [as shipped by the library](https://github.com/nanopb/nanopb/blob/master/extra/FindNanopb.cmake#L122) itself.)

This is the error (CMake v3.16.3):
```
$ cmake ..
-- CPM: adding package nanopb@0.4.5 (0.4.5)
CMake Error at CMakeLists.txt:19 (NANOPB_GENERATE_CPP):
  Unknown CMake command "NANOPB_GENERATE_CPP".


-- Configuring incomplete, errors occurred!
```

Thank you!

**Comment by CodeFinder2** [comment]
Nevermind, I think I was able to fix it with:
```cmake
include(cmake/CPM.cmake)

CPMAddPackage("gh:nanopb/nanopb#0.4.5")
list(APPEND CMAKE_MODULE_PATH ${nanopb_SOURCE_DIR}/extra)
find_package(Nanopb REQUIRED)

NANOPB_GENERATE_CPP(PROTO_SRCS PROTO_HDRS protoc/example.proto)

add_library(${PROJECT_NAME} STATIC ${PROTO_SRCS} ${PROTO_HDRS})
target_include_directories(${PROJECT_NAME} PUBLIC ${NANOPB_INCLUDE_DIRS} ${CMAKE_CURRENT_BINARY_DIR} include)
```

Please let me know if there's a better way. Probably a good idea to add this to your snippet section. ;-)

**Comment by OlivierLDff** [comment]
Using `find_package` seems to defeat the purpose of using `CPM`
