### ISSUE TITLE
Questions regarding making header only libraries with CPM

### ISSUE THREAD

**Issue by Falkgaard** [cpm-cmake/CPM.cmake#298]
Hi! First of all I want to thank you a lot for working hard to make build systems a lot more ergonomic, accessible, and friendlier to idiots and novices alike (and as a member of both groups, I definitely owe you my twice the gratitude!)

Is there a good minimal example somewhere on how to make a simple header-only library repo compatible with CPM?

For example, something like the following structure:

```
MyHeaderOnlyLibrary/CMakeLists.txt
MyHeaderOnlyLibrary/include/MyHeaderOnlyLibrary/core.h
MyHeaderOnlyLibrary/include/MyHeaderOnlyLibrary/info.h
MyHeaderOnlyLibrary/cmake/CPM.cmake
MyHeaderOnlyLibrary/cmake/info.h.in
```

I tried doing it with with `CMakeLists.txt` containing:

```cmake
cmake_minimum_required( VERSION 3.21 FATAL_ERROR ) # TODO: expand version range

project(
	MyHeaderOnlyLibrary
	VERSION     0.1
	DESCRIPTION "Some description."
	LANGUAGES   CXX
)

set                        ( HEADERS core.h info.h )
add_library                ( ${PROJECT_NAME} INTERFACE )
target_sources             ( ${PROJECT_NAME} ${CMAKE_CURRENT_SOURCE_DIR}/include/${PROJECT_NAME}/${HEADERS} )
target_compile_features    ( ${PROJECT_NAME} INTERFACE cxx_std_20 )
target_include_directories ( ${PROJECT_NAME} INTERFACE include/ )

configure_file (
	${CMAKE_CURRENT_SOURCE_DIR}/cmake/info.h.in
	${CMAKE_CURRENT_SOURCE_DIR}/include/${PROJECT_NAME}/info.h
)
```

But then in a project when I do this:

```cmake
cmake_minimum_required ( VERSION 3.21 FATAL_ERROR ) # TODO: expand version range

project (
	MyProject
	VERSION     1.0
	DESCRIPTION "Some description."
	LANGUAGES   CXX
)

add_executable ( ${PROJECT_NAME} src/main.cc )

target_compile_features ( ${PROJECT_NAME} PUBLIC cxx_std_20 )

set( CMAKE_MODULE_PATH "${PROJECT_SOURCE_DIR}/cmake" ${CMAKE_MODULE_PATH} )
include ( cmake/CPM.cmake )
# various other dependencies via CPM here as well
CPMAddPackage( "gh:MyUser/MyHeaderOnlyLibrary@0.1"  )
target_link_libraries      ( ${PROJECT_NAME} PRIVATE   <various others deps here> )
target_link_libraries      ( ${PROJECT_NAME} INTERFACE MyHeaderOnlyLibrary::MyHeaderOnlyLibrary )
target_include_directories ( ${PROJECT_NAME} PUBLIC    "${PROJECT_BINARY_DIR}" )
```

and then build and compile, all the other deps work fine and the header only file appear in the right places in the `MyProject/build/_deps/`; however, it fails to compile (complaining that it can't find the include file of `#include "MyHeaderOnlyLibrary/core.h` (and there's no `-I<path>` flag being passed to the compiler). I've tried following various tutorials (and using stuff like GNUInstallDir) but I always end up with the same issue. I most likely did something wrong (or missed doing something essential), but I have no idea what... :(

**Comment by Andres6936** [comment]
You have not defined an alias for your library, so you cannot link the library as an alias. Try the following in your script:

```diff
cmake_minimum_required ( VERSION 3.21 FATAL_ERROR ) # TODO: expand version range

project (
	MyProject
	VERSION     1.0
	DESCRIPTION "Some description."
	LANGUAGES   CXX
)

add_executable ( ${PROJECT_NAME} src/main.cc )

target_compile_features ( ${PROJECT_NAME} PUBLIC cxx_std_20 )

set( CMAKE_MODULE_PATH "${PROJECT_SOURCE_DIR}/cmake" ${CMAKE_MODULE_PATH} )
include ( cmake/CPM.cmake )
# various other dependencies via CPM here as well
CPMAddPackage( "gh:MyUser/MyHeaderOnlyLibrary@0.1"  )
target_link_libraries      ( ${PROJECT_NAME} PRIVATE   <various others deps here> )
- target_link_libraries      ( ${PROJECT_NAME} INTERFACE MyHeaderOnlyLibrary::MyHeaderOnlyLibrary )
+ target_link_libraries      ( ${PROJECT_NAME} INTERFACE MyHeaderOnlyLibrary)
target_include_directories ( ${PROJECT_NAME} PUBLIC    "${PROJECT_BINARY_DIR}" )
```

**Comment by Falkgaard** [comment]
> You have not defined an alias for your library, so you cannot link the library as an alias. Try the following in your script:
> 
> ```diff
> cmake_minimum_required ( VERSION 3.21 FATAL_ERROR ) # TODO: expand version range
> 
> project (
> 	MyProject
> 	VERSION     1.0
> 	DESCRIPTION "Some description."
> 	LANGUAGES   CXX
> )
> 
> add_executable ( ${PROJECT_NAME} src/main.cc )
> 
> target_compile_features ( ${PROJECT_NAME} PUBLIC cxx_std_20 )
> 
> set( CMAKE_MODULE_PATH "${PROJECT_SOURCE_DIR}/cmake" ${CMAKE_MODULE_PATH} )
> include ( cmake/CPM.cmake )
> # various other dependencies via CPM here as well
> CPMAddPackage( "gh:MyUser/MyHeaderOnlyLibrary@0.1"  )
> target_link_libraries      ( ${PROJECT_NAME} PRIVATE   <various others deps here> )
> - target_link_libraries      ( ${PROJECT_NAME} INTERFACE MyHeaderOnlyLibrary::MyHeaderOnlyLibrary )
> + target_link_libraries      ( ${PROJECT_NAME} INTERFACE MyHeaderOnlyLibrary)
> target_include_directories ( ${PROJECT_NAME} PUBLIC    "${PROJECT_BINARY_DIR}" )
> ```

Hi, thank you for your reply!

Even with that change I get the same error. I put together these two test repos:

<https://github.com/Falkgaard/CMakeTestProject>

which depends on:

<https://github.com/Falkgaard/HeaderOnlyLibTest>

And I clone the former and then build it like this:

```
/CMakeTestProject/
>>  cmake -S . -B build

-- The CXX compiler identification is GNU 11.1.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Downloading CPM.cmake to /home/Foo/Temp/Test/CMakeTestProject/build/cmake/CPM_0.34.0.cmake
-- CPM: adding package HeaderOnlyLibTest@0.1 (v0.1)
-- Configuring done
-- Generating done
-- Build files have been written to: /home/Foo/Temp/Test/CMakeTestProject/build

/CMakeTestProject/
>> cd build

/CMakeTestProject/build/
>> make

[ 50%] Building CXX object CMakeFiles/MyProject.dir/src/main.cc.o
/home/Foo/Temp/Test/CMakeTestProject/src/main.cc:2:10: fatal error: HeaderOnlyLibTest/core.h: No such file or directory
    2 | #include "HeaderOnlyLibTest/core.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/MyProject.dir/build.make:76: CMakeFiles/MyProject.dir/src/main.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:99: CMakeFiles/MyProject.dir/all] Error 2
make: *** [Makefile:91: all] Error 2
```

Any ideas? 🤔

**Comment by TheLartians** [comment]
@Falkgaard  you are linking to the library with `INTERFACE` flags, which will not actually link the library to the target, but only any further derived targets. Try chaining the following in your CMakeTestProject `CMakeLists.txt`:

```diff
-- target_link_libraries      ( ${PROJECT_NAME} INTERFACE MyHeaderOnlyLibrary::MyHeaderOnlyLibrary )
++ target_link_libraries      ( ${PROJECT_NAME} PUBLIC MyHeaderOnlyLibrary::MyHeaderOnlyLibrary )
```

**Comment by Falkgaard** [comment]
> 

Thank you so much, that fixed it!
