### ISSUE TITLE
Confused by the build stage

### ISSUE THREAD

**Issue by amirmasoudabdol** [cpm-cmake/CPM.cmake#299]
I am wondering if someone could help me understand an issue that I have with the CPM. I can integrated it, no problem. But for some reason, when I build my project. CPM starts to mix up everything. It creates a `lib`, and `bin` directory in my build directory and shuffles everything around. I don't exactly know what happened that CPM doesn't put things in their respected `-build`, `-install` folders anymore. 

I should probably mention that I'm using the `ExternalPackage` as well, and direct them to the same `_deps` directory. But, I don't think that should cause the problem. I feel that somehow, CPM triggers an install target for some reason! I am not sure. 

Thanks for your help in advance!

**Comment by amirmasoudabdol** [comment]
So, here is a bit of context. As you can see, I am using the CPM to build Boost. From version 1.77.0 or so Boost comes with a native `CMakeLists.txt`, so, that is why I can just use that. Beside the packages that I'm installing from CPM, I'm also download the `readstat` and setup and installing it using the `ExternalPackage_Add` as you can see below. 

I actually think, while I was writing this, I somehow answered my own question. So, is it the case that CPM triggers the install before it sees that `ExternalPackage_Add` has triggered it? If that is the case, then my question morphs into, how to stop CPM from doing that?

```
cpmaddpackage(
  NAME
  Boost
  VERSION
  1.78.0
  OPTIONS
  "BUILD_TESTING OFF"
  GITHUB_REPOSITORY
  "boostorg/boost"
  GIT_TAG
  "boost-1.78.0.beta1")

cpmaddpackage(
  NAME
  jsoncpp
  VERSION
  1.9.5
  OPTIONS
  "JSONCPP_WITH_TESTS OFF"
  "JSONCPP_WITH_POST_BUILD_UNITTEST OFF"
  GITHUB_REPOSITORY
  "open-source-parsers/jsoncpp"
  GIT_TAG
  "1.9.5")

externalproject_add(
  readstat
  PREFIX _deps/readstat
  GIT_REPOSITORY "https://github.com/WizardMac/ReadStat"
  GIT_TAG "v1.1.7"
  BUILD_IN_SOURCE ON
  STEP_TARGETS configure build install
  CONFIGURE_COMMAND ./autogen.sh
  COMMAND autoupdate
  COMMAND ./configure --prefix=<DOWNLOAD_DIR>/readstat-install
  BUILD_COMMAND ${MAKE})

externalproject_get_property(readstat DOWNLOAD_DIR)
set(readstat_DOWNLOAD_DIR ${DOWNLOAD_DIR})
set(readstat_BUILD_DIR ${readstat_DOWNLOAD_DIR}/readstat-build)
set(readstat_INCLUDE_DIRS ${readstat_DOWNLOAD_DIR}/readstat-install/include)
set(readstat_LIBRARY_DIRS ${readstat_DOWNLOAD_DIR}/readstat-install/lib)

```

**Comment by foobar442130** [comment]
> It creates a `lib`, and `bin` directory in my build directory and shuffles everything around. I don't exactly know what happened that CPM doesn't put things in their respected `-build`, `-install` folders anymore.

That is likely one of the projects cmake code causing that. Not CPM. They most likely change how their build directory is laid out.

Some projects are friendly to `add_subdirectory` like [GSL](https://github.com/Microsoft/GSL) but some aren't.

See this page for more info:
https://github.com/cpm-cmake/CPM.cmake/wiki/Preparing-projects-for-CPM.cmake

**Comment by foobar442130** [comment]
Here is the code that is causing the issue you described.

Their mistake is not using CMAKE_CURRENT_BINARY_DIR

```
set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/lib" CACHE PATH "Archive output dir.")
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/lib" CACHE PATH "Library output dir.")
set(CMAKE_PDB_OUTPUT_DIRECTORY     "${CMAKE_BINARY_DIR}/bin" CACHE PATH "PDB (MSVC debug symbol)output dir.")
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/bin" CACHE PATH "Executable/dll output dir.")
```

**Comment by foobar442130** [comment]
This caused by the json-cpp projects cmake code.

Basically json-cpp only works well as a top-level project.

https://cmake.org/cmake/help/latest/variable/PROJECT-NAME_IS_TOP_LEVEL.html?highlight=top%20level

Some projects write their CMake assuming they will be installed. Not added via add_subdirectory.

Which means FetchContent/CPM don't work nicely with them.

Package managers like conan/vcpkg work better with those types of libraries.

**Comment by foobar442130** [comment]
Basically before FetchContent/CPM the way to use other peoples libraries was like this:

```
cmake -S . -B build/
cmake --build build/
cmake --install ...
```

# And then that will install the binaries to a location on the system, and you use find_package in your cmake code
conan/vckpg streamline this workflow.

There are pros/cons as noted here:
https://github.com/cpm-cmake/CPM.cmake#advantages
https://github.com/cpm-cmake/CPM.cmake#limitations

**Comment by amirmasoudabdol** [comment]
> Here is the code that is causing the issue you described.
> 
> Their mistake is not using CMAKE_CURRENT_BINARY_DIR
> 
> ```
> set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/lib" CACHE PATH "Archive output dir.")
> set(CMAKE_LIBRARY_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/lib" CACHE PATH "Library output dir.")
> set(CMAKE_PDB_OUTPUT_DIRECTORY     "${CMAKE_BINARY_DIR}/bin" CACHE PATH "PDB (MSVC debug symbol)output dir.")
> set(CMAKE_RUNTIME_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/bin" CACHE PATH "Executable/dll output dir.")
> ```

I can see it now, and it makes sense. So, my guess was right, but I just thought CPM is doing something strange, but nope, it was one of the packages. I have tested it without it and it works just fine like it should.

So, one way to fix this is to remove those files for instance, and then pass it to the CPM but with CPM I don't have the control that I have with `ExternalProject`! 🤔 I really like CPM because it automatically include the target, and etc, but I'm not sure about the `ExternalProject`. If I do this with the `ExternalProject`, then I have to collect all the paths and include them manually like I did for `readstat` in my example, right?

Thanks a bunch for your help! 🙏🏼🙂

**Comment by amirmasoudabdol** [comment]
I see that it is not that simple. It feels like that they have intentionally tried to avoid a modern CMake build tree.

**Comment by foobar442130** [comment]
Yeah not all libraries are friendly to being consumed via add_subdirectory.

jsoncpp clearly expects you to install it. Not use add_subdirectory. That's the larger issue.

**Comment by amirmasoudabdol** [comment]
I asked them if they are willing to change that, if so, I can look into it and help them get it right!

**Comment by amirmasoudabdol** [comment]
If I installed it using the `ExternalPackage` can I set the `CMAKE_INSTALL_PREFIX` that it installs it into its own place instead of messing everything else?

**Comment by foobar442130** [comment]
I'd close this issue for now so it's potentially more useful to other people in the future.

What I will recommend is this book for cmake:
https://crascit.com/professional-cmake/

**Comment by amirmasoudabdol** [comment]
Thanks a lot for your help! I have the book and I have already learned a lot! 🙏🏼

**Comment by foobar442130** [comment]
No worries. The book has a section on it I just haven't had to use it too much yet.

**Comment by amirmasoudabdol** [comment]
One last update, so, I can force `jsoncpp` that is being installed using the `ExternalProject` to respect the build directory by pushing its install location to where I want by using this, `-DCMAKE_BINARY_DIR=<DOWNLOAD_DIR>/jsoncpp-install`. I hope this doesn't have any strange effect and `ExternalProject` manages to keep it separated from the rest.

**Comment by foobar442130** [comment]
It's worth considering looking at conan as well:
https://conan.io/center/jsoncpp

jsoncpp is listed as a package there. I'm not saying CPM isn't great because it's fantastic when libraries are written with good CMake. However, good library + good cmake is a hard combination.

Our company is looking into conan. Perhaps you might benefit from looking into it as well.

**Comment by amirmasoudabdol** [comment]
I don't think that's an option for us, we are bound to Qt, and Qt comes with its own difficulties. It's already a blessing that they are going to drop QMake, and moving into the CMake. That's why I am trying to get everything working with CMake. I have not idea if Qt likes Conan or not, and how they work around it. In addition, CMake does a lot of post build that we really like!

**Comment by foobar442130** [comment]
CMake works with Conan. Conan isn't a different build system. It's a package manager that facilitates CMake.

**Comment by foobar442130** [comment]
I like CPM but it may not be the solution for working with libraries like boost/qt.

Granted I still need to learn more about both tbh. So I'm NO authority on conan vs CPM vs vcpkg.
