### ISSUE TITLE
DOWNLOAD_ONLY not works together with CPM_pkg_SOURCE

### ISSUE THREAD

**Issue by hacker-cb** [cpm-cmake/CPM.cmake#307]
I'm using `DOWNLOAD_ONLY YES` flag to just download package, without calling `add_subdirectory()`.

This behaviour does not work if I manually set `CPM_pkg_SOURCE` variable to use existing package location during development. 

Internally, CPM recursivelly calls CPMAddPackage() inside `CPMAddPackage()` [here](https://github.com/cpm-cmake/CPM.cmake/blob/dad37fbe4e7a64c42918159402847939265bcda1/cmake/CPM.cmake#L545).

But argument `DOWNLOAD_ONLY` is not passed to this recursive call.

So, is this normal or bug?

As workaround I'm using unexisting `SOURCE_SUBDIR` to skip `add_subdirectory()` call.

**Comment by hacker-cb** [comment]
I made PR for this case.

**Comment by TheLartians** [comment]
Looks like an oversight to me, thanks for the issue and PR!
