### ISSUE TITLE
CPM add support for projects that don't have good CMakeLists.txt

### ISSUE THREAD

**Issue by foobar442130** [cpm-cmake/CPM.cmake#309]
"Dependent on good CMakeLists Many libraries do not have CMakeLists that work well for subprojects. Luckily this is slowly changing, however, until then, some manual configuration may be required (see the snippets below for examples). For best practices on preparing projects for CPM, see the wiki."

Instead of waiting on this. Couldn't we install the project for the user? Many project offer `install` and `find_package` capabilities.

So instead of calling add subdirectory we run run the regular CMake steps for the user.

1.) Generate project
2.) Build project
3.) Install project
4.) Use `find_package` afterwards in the CMake code

Shouldn't this be a viable solution? I don't want to fix everyone's CMake code.

**Comment by TheLartians** [comment]
Hey thanks for the issue! I definitely feel your pain of updating old CMake projects to work as a dependency / subdirectory. Unfortunately, building and installing dependencies is also highly nontrivial, as the project would not only need to be installable, but also support and receive any compiler flags, toolchains etc. that have been set by the parent project.
