### ISSUE TITLE
Upstreaming an easy way to use third party modules

### ISSUE THREAD

**Issue by foobar442130** [cpm-cmake/CPM.cmake#310]
I really think the best avenue for easy adoption of CMake modules is to have CMake officially handle third party module support.

I'd really like to have something like this:
```
cmake_module_manager(GIT_URL "https://github.com/cpm-cmake/CPM.cmake" TAG "0.34.0")
```

Ideally this would achieve the same result as this:
https://github.com/cpm-cmake/CPM.cmake/wiki/Downloading-CPM.cmake-in-CMake

Except cmake_module_manager would cache by default and by part of upstream CMake. So I can write less code to use other peoples CMake 😁

Thoughts?

**Comment by foobar442130** [comment]
Let me know if you are interested and I'd be more than happy to help out 👍

**Comment by TheLartians** [comment]
Hey, thanks for the suggestion, I agree that it would be a neat to have official third party package / module support in CMake. However you may want to forward the question to an official CMake repo or forum as this project isn't affiliated with them in any way.
