### ISSUE TITLE
CMake warning on development version

### ISSUE THREAD

**Issue by eyalamirmusic** [cpm-cmake/CPM.cmake#311]
Seems like the most current version on the master branch is reporting a development version which throws a CMake warning when configuring.

Will it be possible to keep those warnings away from the master branch, perhaps using another branch for the dev versions?

**Comment by TheLartians** [comment]
Hey, thanks for the issue! The warning is indeed intentional as we do active development on the master branch and the code may be unstable. To remove the warning, use a [released version](https://github.com/cpm-cmake/CPM.cmake/releases) of CPM.cmake.
