### ISSUE TITLE
Whitespaces in paths inside of generated find cmake modules

### ISSUE THREAD

**Issue by DNKpp** [cpm-cmake/CPM.cmake#312]
Hopefully someone can light me up, but as far as I understand CPM creates inside of ``<outdir>/CPM_modules`` ``Findxyz.cmake`` files for each dependency, which might be used from my own or third-party CMakeLists.txt. Unfortunatly those absolute paths are not wrapped inside of ``"``, thus cmake won't be able to generate if any path contains a whitespace.
Is there anything I can do to get around this (beside getting rid of whitespaces in the absolute path)?

Greetings

**Comment by TheLartians** [comment]
Hey, thanks for the issue! Yeah this looks as an oversight as we are not quoting the arguments to the `CPMAddPackage` call in the module file, resulting in CMake using whitespaces as additional separators. I think simply quoting all arguments should allow using whitespaces.

**Comment by TheLartians** [comment]
Fix is published in `v0.34.3`!
