### ISSUE TITLE
Using of dynamic vMajor.Minor tags

### ISSUE THREAD

**Issue by DNKpp** [cpm-cmake/CPM.cmake#318]
Currently its rather tedious tkeeping all projects using CPM up2date. I use the ``get_cpm`` module, which works quite nice. I think it would be a great improvement, if CPM keeps additional dynamic ``vMajor.Minor`` tags, which will then be moved to the current active patch tag. These tags could then be targeted by the ``get_cpm`` module.
Image a tag ``v0.42``. Then patch  ``v0.42.1`` comes out and the ``v0.42`` tag will be reset to point exactly to the same commit as the ``v0.42.1``. But it will not move to a ``v0.43.x`` patch.

As patches usually don't break anything but patches bugs, that should be a preferable behaviour.

**Comment by TheLartians** [comment]
> As patches usually don't break anything but patches bugs, that should be a preferable behaviour.

In a perfect world yes, but mistakes are easily made. Tbh I prefer strict versioning as it would guarantee reproducibility in all circumstances. Perhaps an auto-update feature (that would override the version in cmake or in a version lock file) would be nice instead.

**Comment by saxbophone** [comment]
Maybe a `SEMVER` option in `CPMFindPackage()` that is an alternative to `VERSION`, and which is an explicit assertion by the user that they trust their upstream dependency follows semantic versioning and they are happy to have the `v0.4 binds to v0.4.x` behaviour that is mentioned?

**Comment by TheLartians** [comment]
In general I think it's a nice idea, however should come together with proper lockfile support so that we can still commit exact versions into our repositories.
