### ISSUE TITLE
List of contributors

### ISSUE THREAD

**Issue by iboB** [cpm-cmake/CPM.cmake#339]
This was raised as an issue in #335:  There is no list of individual contributors associated with the project. Such lists exist in many open source projects

For example here's what the best documented (IMO) open source project does: https://doc.magnum.graphics/magnum/credits-contributors.html

Doing something similar in terms of content is a lot of work. We would have to go through every single PR in order to match a contributor with what they've done.

So, instead I suggest we add `CONTRIBUTORS.md` where we list people from [this page](https://github.com/cpm-cmake/CPM.cmake/graphs/contributors) with links to their GitHub profiles and take it from there.

What to do with companies? If someone does contributions on company time, they would likely want to add the company as a contributor, as it seems to be the case with @robertmaynard 

@robertmaynard, how about we have your entry in the future `CONTRIBUTORS.md` look like this:

*  NVIDIA CORPORATION via [Robert Maynard](https://github.com/robertmaynard)

**Comment by robertmaynard** [comment]
This sounds very reasonable to me
