### ISSUE TITLE
Handling of SSH key and it's Passphrase for git repos

### ISSUE THREAD

**Issue by Mebus** [cpm-cmake/CPM.cmake#347]
Hallo folks,

CPM works nice for us, except for a problem with the SSH key and it's Passphrase for remote git repositories when we use the CMake Projekt in QtCreator or another IDE on Windows. It seems that the CMake git client does not connect to any SSH agent, neither the Windows internal SSH agent nor pageant.exe. What is a proper way to fix this?

Thanks!

Mebus

**Comment by shrkamat** [comment]
It will be good if you could paste your  `GIT_REPOSITORY` url along with CPMAddPackage config.

**Comment by Mebus** [comment]
I fixed it by using the standard windows ssh-agent.

Mebus
