### ISSUE TITLE
Include "built" header-only libraries with CPM.

### ISSUE THREAD

**Issue by hameer-spire** [cpm-cmake/CPM.cmake#354]
Hello,

First of all, thanks for the awesome library!

I'm trying to include header-only libraries that only have a valid configuration and all targets after they're _built/installed_, for example https://github.com/xtensor-stack/xtensor. In this case, the "build" directory is the actual source directory. Is there a way to handle this?

**Comment by TheLartians** [comment]
Hey, it depends on the implementation of the library, but a simple way could be to create an interface target that includes the directory with the generated header. I believe you should be able to use [`add_dependencies`](https://cmake.org/cmake/help/latest/command/add_dependencies.html) to ensure that the header gets built before dependent targets that use them.

If the library doesn't behave well with CMake you should be able to create a target that uses an external script through [`add_custom_command`](https://cmake.org/cmake/help/latest/command/add_custom_command.html).

In any case this seems more CMake related than package management, so it could make sense to ask the question at [discourse.cmake.org](https://discourse.cmake.org) as well.

**Comment by oddko** [comment]
If it's header only, you're pretty much better off creating an interface library target yourself (e.g. `add_library(xtensor INTERFACE)`), add an `INTERFACE` include directory with the path to the `include/` directory that you got using CPM, and calling it a day. That's how I do it for Eigen and it works very well.

**Comment by hameer-spire** [comment]
@oddko Would it be possible for you to link me to a code snippet, if it's not proprietary?

**Comment by oddko** [comment]
Sure thing (note that it uses relative repositories that are added in this PR https://github.com/cpm-cmake/CPM.cmake/pull/333)

```cmake
CPMAddPackage(
        RELATIVE_REPOSITORY ../eigen
        GIT_TAG 3.4.0
        VERSION 3.4.0
        GIT_SHALLOW TRUE
        DOWNLOAD_ONLY TRUE)

if (eigen_ADDED)
    add_library(eigen INTERFACE)
    target_include_directories(eigen INTERFACE "${eigen_SOURCE_DIR}")
    if (MSVC)
        # For compilers below MSVC2019, ask for extended aligned storage
        if (${MSVC_VERSION} VERSION_LESS 1920)
            target_compile_definitions(eigen INTERFACE _ENABLE_EXTENDED_ALIGNED_STORAGE)
        endif()
    endif()
endif()
```
