### ISSUE TITLE
Optimization: Reuse a dependency repo in a specified folder after version change

### ISSUE THREAD

**Issue by danra** [cpm-cmake/CPM.cmake#355]
I'd like a feature to allow specifying a folder for a dependency, to be used even if the dependency commit changes, upon which the dependency repo will be updated from the remote and the desired commit will be checked out (unlike the [existing Local Package Override feature](https://github.com/cpm-cmake/CPM.cmake#local-package-override) which just takes what's in the given folder as is).

**Why I'd like this feature:**

I've started using CPM instead of git submodules for managing not just dependencies on external packages with proper releases, but also dependencies on some of our local libraries which change often.

Using CPM for this purpose gives some advantages:
1) Listing all dependencies, both local private and external public ones, in one place. 
2) Warn on mismatching dependencies (A depends on B and C, B depends on different version of C), vs. just take re-cloning and checking out different versions of the local dependencies at different nesting levels).

However, the performance in my use case is terrible: every time I make on update to the commit I depend on, CPM re-clones the remote into a separate directory. This makes for the multiple-versions-of-the-same-library-installed-on-same-machine use case, but it is needlessly slow for my use case of just working on a single project which has frequent updates to its local dependencies.

I can imagine this being implemented either as a flag for changing the behavior of the existing "Local package override" feature, or just as a new option.

**Comment by oddko** [comment]
So in a way you are looking for a project-scoped "CPM_SOURCE_CACHE" that keeps a single clone per dependency and checks it out instead of making a clone per tag/commit hash ?

**Comment by danra** [comment]
@oddko Thanks, it looks like the behavior without CPM_SOURCE_CACHE was just what I'm looking for.
