### ISSUE TITLE
How to use `CPM_SOURCE_CACHE` on windows

### ISSUE THREAD

**Issue by ShaneKosieradzki** [cpm-cmake/CPM.cmake#365]
The wiki says to set `CPM_SOURCE_CACHE` in `.bashrc`, which is not used in standard windows environment. 

Using CMake's `set` command does not seem to work either.

**Comment by oddko** [comment]
Either use a powershell profile if you want a .bashrc like solution, or add it system-wide in the "environment variables" settings of Windows.

**Comment by iboB** [comment]
https://docs.oracle.com/en/database/oracle/machine-learning/oml4r/1.5.1/oread/creating-and-modifying-environment-variables-on-windows.html

**Comment by iboB** [comment]
I think we can consider this closed
