### ISSUE TITLE
My own library does not work and failes to compile with headers not being found internally

### ISSUE THREAD

**Issue by XFaonAE** [cpm-cmake/CPM.cmake#369]
My library im trying to make CPM compile is at SkylixGH/Elixor
I also relized other dependencies i tried installing with CPM dont work because the library name isnt found by target_link_libraries, how do i find out the library name for a package

**Comment by iboB** [comment]
Which library is that?

**Comment by XFaonAE** [comment]
Oh i fixed it, my lib had a bug sorry
