### ISSUE TITLE
Use Renovate to update versions

### ISSUE THREAD

**Issue by JohT** [cpm-cmake/CPM.cmake#389]
I recently wrote a blog article about how to customize [Renovate](https://github.com/renovatebot/renovate) to automatically update dependency versions in [package-lock.cmake](https://github.com/cpm-cmake/CPM.cmake/wiki/Package-lock) and the download of CPM.cmake itself: 

[Keep your C++ dependencies up-to-date with Renovate & CPM](https://joht.github.io/johtizen/automation/2022/08/03/keep-your-cpp-dependencies-up-to-date.html)

I thought this might be helpful for others here...

**Comment by TheLartians** [comment]
Hey this looks really neat, thanks for sharing!

**Comment by JohT** [comment]
Since this isn't an open issue, I'll close it.
