### ISSUE TITLE
Do we have a good way to incorporate OpenSSL / BoringSSL with CPM?

### ISSUE THREAD

**Issue by MrJia1997** [cpm-cmake/CPM.cmake#405]

**Comment by CraigHutchinson** [comment]
I have not tried myself but for non CMake projects a wrapper approach is commonly used. First one I spotted is this one which may be of help?   https://github.com/viaduck/openssl-cmake

You 'should' be able to pull this using CPM but as it may be using bare FetchContent calls the cache behavior may not be ideal - making a issue/pull to that repo to use CPM could be one approach or find alternative wrappers.

**Comment by bsergean** [comment]
Just a quick word of caution, I tried to use a similar cmake openssl project recently, and it got all the compiler options wrong it seemed (like no assembly was used, for computing AES for example), so the code was much slower. So make sure your openssl-cmake wrapper works well in this respect.

**Comment by MrJia1997** [comment]
Thank you for your response!
It turns out that the `CMakeLists.txt` comes with BoringSSL can perfectly fit CPM, though in general BoringSSL isn't recommended for non-Google projects, and it doesn't have release / LTS versions. However, it solves my problem, and my projects runs!
