### ISSUE TITLE
project_options_SOURCE_DIR variable is not set with short git url?

### ISSUE THREAD

**Issue by ClausKlein** [cpm-cmake/CPM.cmake#407]
It seems to me the `<dependency>_SOURCE_DIR` is the path to the source of the dependency.
 
But it is only set if `NAME` parameter is given?

```cmake
CPMAddPackage("gh:aminya/project_options@0.25.1")
list(APPEND CMAKE_MODULE_PATH ${ProjectOptions_SRC_DIR})# NOTE: set from project_options
# FIXME list(APPEND CMAKE_MODULE_PATH ${project_options_SOURCE_DIR}/src) # should be set from CPM.cmake
```

**Comment by CraigHutchinson** [comment]
With the Single-Argument approach the name is determined internally. As you identify it 'Should' be `project_options` but could be worth checking if this is the case. There is a Pull-Request for this issue that provides `CPM_LAST_PACKAGE_NAME` which will confirm if the name is coming out correctly for your use-case https://github.com/cpm-cmake/CPM.cmake/issues/400

**Comment by ClausKlein** [comment]
> With the Single-Argument approach the name is determined internally.

yes, but as an empty string, so your `CPM_LAST_PACKAGE_NAME` would also be empty!

**Comment by ClausKlein** [comment]
see https://github.com/cpm-cmake/CPM.cmake/pull/409

**Comment by CraigHutchinson** [comment]
> > With the Single-Argument approach the name is determined internally.
> 
> yes, but as an empty string, so your `CPM_LAST_PACKAGE_NAME` would also be empty!

The name is determined by extracting form the URI as add-package is called recursively. Well done for spotting the issue in your use-case. You should find that with your fix the value of `CPM_LAST_PACKAGE_NAME` will now be set, confirms my suspicions :)

**Comment by TheLartians** [comment]
@ClausKlein I can't seem to reproduce the issue, perhaps you meant `project_options_SOURCE_DIR` instead of `ProjectOptions_SRC_DIR`?

The example below works fine for me.

<details> 

```cmake
cmake_minimum_required(VERSION 3.14 FATAL_ERROR)

project(Playground LANGUAGES CXX)

# ---- Fetch CPM ----

set(CPM_DOWNLOAD_VERSION 0.35.6) 
set(CPM_DOWNLOAD_LOCATION "${CMAKE_BINARY_DIR}/cmake/CPM_${CPM_DOWNLOAD_VERSION}.cmake")
if(NOT (EXISTS ${CPM_DOWNLOAD_LOCATION}))
  message(STATUS "Downloading CPM.cmake v${CPM_DOWNLOAD_VERSION}")
  file(DOWNLOAD https://github.com/cpm-cmake/CPM.cmake/releases/download/v${CPM_DOWNLOAD_VERSION}/CPM.cmake ${CPM_DOWNLOAD_LOCATION})
endif()
include(${CPM_DOWNLOAD_LOCATION})

# Run `cmake --build build --target cpm-update-package-lock` to update the package lock.
CPMUsePackageLock(package-lock.cmake)

# ---- Add dependencies ----

CPMAddPackage("gh:aminya/project_options@0.25.1")
message("The source project_options source directory is: ${project_options_SOURCE_DIR}")
```

</details>

**Comment by ClausKlein** [comment]
> @ClausKlein I can't seem to reproduce the issue, perhaps you meant `project_options_SOURCE_DIR` instead of `ProjectOptions_SRC_DIR`?
> 
> The example below works fine for me.

My fault.
I used first this: `list(APPEND CMAKE_MODULE_PATH ${project_options_SOURCE_DIR})`
