### ISSUE TITLE
How to skip `cpm_check_git_working_dir_is_clean`

### ISSUE THREAD

**Issue by OlivierLDff** [cpm-cmake/CPM.cmake#419]
Hi, when benchmarking cmake run with `cmake --profiling-format=google-trace --profiling-output=perf.json ..` I find that some huge repo takes couple of hundred of milliseconds to run  `cpm_check_git_working_dir_is_clean`.
I would like to be able to skip this check.

I see in source code:
https://github.com/cpm-cmake/CPM.cmake/blob/03705fcce165c7eb2680e4c7d8a272cfb0a1061a/cmake/CPM.cmake#L715-L721

It seems to be possible to skip it by adding `PATCH_COMMAND`, but this is per target. Is there any other way I've missed to disable the check? Ideally some `-DCPM_CHECK_GIT_WORKING_DIR_IS_CLEAN=OFF` that I can apply everywhere.
I would be happy to provide a PR, but I guess some discussion on how to do things is therefore required.

Here is also an example of benchmark:
![image](https://user-images.githubusercontent.com/17255804/197334067-9db930f3-c297-477c-92f0-aea5f7bfd2a3.png)

As you can see, it's not lots of time, but when there is 20-30 projects, it can takes couple of seconds.

Have a nice day.

**Comment by CraigHutchinson** [comment]
This is a nice issue, performance of build is always important.

`git status` can be very slow for larger repositories and does depend on the file-system in use. A workaround may be to configure git status to not show untracked files for the clones [status.showUntrackedFiles false](https://stackoverflow.com/a/10824022/876651)
