### ISSUE TITLE
Handling a case when public header structure is generated on install

### ISSUE THREAD

**Issue by shakfu** [cpm-cmake/CPM.cmake#435]
I have case where I'm a bit stuck. This is [an example](https://github.com/ivmai/bdwgc) of a package where the public header structure is different from the private header, and the public header is generated on install. The project itself uses cmake.

```cmake
CPMAddPackage(
    NAME bdwgc
    GITHUB_REPOSITORY "ivmai/bdwgc"
    VERSION 8.0.5
    GIT_TAG d0ba209660ea8c663e06d9a68332ba5f42da54ba
    OPTIONS "CMAKE_POSITION_INDEPENDENT_CODE ON"
            "BUILD_SHARED_LIBS OFF"
            "enable_threads ON"
            "enable_large_config ON"
            "enable_thread_local_alloc ON"
            "enable_cplusplus ON"
            "enable_handle_fork ON")
```

When I add it's components as dependencies to my project, it gives an error because the uninstalled private headers do not corresponds to its public headers: fatal error: 'gc/gc_allocator.h' file not found #include <gc/gc_allocator.h>

I ended up writing a bash script to do this manually:

```bash
deps_dir=`pwd`/build/deps
src_dir=${deps_dir}/src

# make src_dir
mkdir -p ${src_dir}
cd ${src_dir}

# download / build / install bdwgc
echo "download / build / install bdwgc"
git clone --depth=1 https://github.com/ivmai/bdwgc
cd bdwgc
mkdir build && cd build
cmake .. \
	-DCMAKE_INSTALL_PREFIX:PATH=${deps_dir} \
	-DBUILD_SHARED_LIBS=OFF \
	-Denable_cplusplus=ON \
	-Dbuild_cord=OFF \
	-Denable_docs=OFF \
	-Denable_gcj_support=OFF \
	-Denable_java_finalization=OFF
make install
```

Is there any way to do the equivalent with CPM + cmake? i.e. force an install of a dependency at generation time or build time?

**Comment by shakfu** [comment]
I think my issue is related to [Issue 373](https://github.com/cpm-cmake/CPM.cmake/issues/373)

**Comment by TheLartians** [comment]
Currently CPM.cmake has no plans to support packages that generate files on install as opposed to build stages. While this would be nice to have, a roadblock is I'm not aware of a reliable way to forward all CMake configuration options, toolchains, compiler settings, etc. to the child process. For example, if the library is not header only, you would not be able to cross-compile for another platform unless you forward all required toolchain and configuration settings.

For these use-cases I recommend using either `ExternalProject` or requesting that the dependency changes their build script to creates all source files during the build phase instead.

**Comment by shakfu** [comment]
@TheLartians Fair enough. Thanks for your response and clarification.
