### ISSUE TITLE
Proposal: specify where CMakeLists.txt is for external package

### ISSUE THREAD

**Issue by ethindp** [cpm-cmake/CPM.cmake#469]
This is something that I could definitely use, and I imagine others could too. As an example, the zstd compression library has a CMakeLists.txt file, but it isn't at the top level of the source tree. The LLVM project has CMake project files for each subproject, not at the top level. (They used to, but that's since changed.) As it currently stands, I can add these with `CPMAddPackage` but they never get configured.

**Comment by TheLartians** [comment]
Good idea, this sounds like a very useful feature!

**Comment by PercentBoat4164** [comment]
I had this same issue with GLEW. I solved it with
```CMake
CPMAddPackage(
        NAME glew
        URL https://github.com/nigels-com/glew/releases/download/glew-2.2.0/glew-2.2.0.tgz
        VERSION 2.2.0
        SOURCE_SUBDIR build/cmake
)
```
in which the `SOURCE_SUBDIR` argument points to the directory that contains the CMakeLists.txt file. Is this what you were looking for?

**Comment by ethindp** [comment]
Yes, I didn't know that was possible, thanks!
