### ISSUE TITLE
DOWNLOAD_COMMAND doesn't work with multi-token string

### ISSUE THREAD

**Issue by jm4R** [cpm-cmake/CPM.cmake#472]
Example:

```
CPMAddPackage(NAME test DOWNLOAD_COMMAND svn export https://path/to/file.zip)
```

...causes FetchContent to call `svn` without any arguments.

**Comment by jm4R** [comment]
No, it doesn't work that way. With quotes it treats it like command with spaces and without arguments and causes "command not found". When you pass such arguments to FetchContent_Declare, it works good.

**Comment by TheLartians** [comment]
Ah I see. So it seems the download command should be actually a multi-value argument instead of a single one as we define it when calling `cmake_parse_arguments`. Sorry for the confusion, I'll prepare a PR to fix it.
