### ISSUE TITLE
OVERRIDE_FIND_PACKAGE doesn't work

### ISSUE THREAD

**Issue by patstew** [cpm-cmake/CPM.cmake#498]
I think because CPM avoids calling FetchContent_MakeAvailable(?), the OVERRIDE_FIND_PACKAGE argument to FetchContent_Declare doesn't work. The redirect files don't get created.

**Comment by anthonyalayo** [comment]
I found this issue after looking into the same thing. @TheLartians , could this get attention?

**Comment by TheLartians** [comment]
Unfortunately I currently don't have the time to look into this, but would be very happy to review a PR that suggests a fix.

**Comment by ethindp** [comment]
I'm running into this bug too: a dependency requires pugixml, and even though I included it via `CPMAddPackage` it still claims it can't find it.

**Comment by ethindp** [comment]
Odd thing is that it worked fine a couple days ago, I have no idea what changed.
