### ISSUE TITLE
Honour new relative git URL behaviour controlled by CMP0150

### ISSUE THREAD

**Issue by inkychris** [cpm-cmake/CPM.cmake#520]
I added support for relative git URLs to FetchContent/ExternalProject which was introduced in cmake v3.27 under policy [CMP0150](https://cmake.org/cmake/help/latest/policy/CMP0150.html). Unfortunately, this doesn't seem to work when wrapped with CPM and it looks like this is because CPM minimum cmake version is set to 3.14.

I'm not sure on the best strategy here, but one option would be for CPM to inherit the policies from the parent project, and just assert that they're set at least to a minimum of 3.14 as CPM needs, rather than actually explicitly setting them to 3.14 as is currently the case. Alternatively, it should at least honour policy 150 and pass it through if it can.

Happy to submit a PR for this if there's a preferred solution.

**Comment by TheLartians** [comment]
Hey, thanks for raising the issue, I agree that it would make sense for CPM to honour the new policy. Currently we handle overriding policies inside a dedicated [macro](https://github.com/cpm-cmake/CPM.cmake/blob/a9c8c6fe1b4140bd08a73df5d4cc478cda39817b/cmake/CPM.cmake#L85) (see [here](https://github.com/cpm-cmake/CPM.cmake/issues/387) for discussion), which would be the preferred location to enable CMP0150. Would be very happy to review a PR for this!

**Comment by inkychris** [comment]
Sure thing, I'll submit a PR!
