### ISSUE TITLE
wxWidgets example

### ISSUE THREAD

**Issue by idotta** [cpm-cmake/CPM.cmake#523]
Hi there! Would someone please show me an example on how to use CPM to build a project using wxWidgets?

I couldn't make it work and I'm not experienced with CMake. I know there's something missing, but I can't figure out what. I'm trying to do it simply by using:

```
CPMAddPackage("gh:wxWidgets/wxWidgets@3.2.4")
include(${wxWidgets_USE_FILE})
add_executable(app main.cpp)
target_link_libraries(app PRIVATE ${wxWidgets_LIBRARIES})
```

**Comment by jolz** [comment]
Hi. you missed to give some error message...

The following snippet works for me (linux, all required -dev-Packages installed).

```cmake
cmake_minimum_required(VERSION 3.24)

include(${CMAKE_SOURCE_DIR}/cmake/CPM.cmake)
CPMAddPackage("gh:wxWidgets/wxWidgets@3.2.5")

project(hello CXX)
add_executable(${PROJECT_NAME} WIN32 hello.cpp)
target_link_libraries(${PROJECT_NAME} PRIVATE wx::core)
```

**Comment by idotta** [comment]
Hi there! Thank you so much for taking the time for a complete example!
