### ISSUE TITLE
CMake 3.30: FetchContent_Populate(package_name) is deprecated

### ISSUE THREAD

**Issue by Mrkol** [cpm-cmake/CPM.cmake#588]
Something changed in CMake and I now get this warning every time CPM downloads a package

[cmake] CMake Warning (dev) at C:/Program Files/CMake/share/cmake-3.30/Modules/FetchContent.cmake:1953 (message):
[cmake]   Calling FetchContent_Populate(MY_PACKAGE_NAME) is deprecated, call
[cmake]   FetchContent_MakeAvailable(MY_PACKAGE_NAME) instead.  Policy CMP0169 can be set to OLD
[cmake]   to allow FetchContent_Populate(MY_PACKAGE_NAME) to be called directly for now, but the
[cmake]   ability to call it with declared details will be removed completely in a
[cmake]   future version.

**Comment by Avus-c** [comment]
This is odd - it should've been fixed in release [v0.40.1](https://github.com/cpm-cmake/CPM.cmake/releases/tag/v0.40.1).

Did you update CPM? If the warning is still showing in the new version, could you provide a code snippet showing how you're using CPM? We may have overlooked something in the fix (#570).

**Comment by Mrkol** [comment]
Ooooh, my bad, for some reason I though that the get_cpm.cmake automatically downloads the latest version. Issue is gone after updating, thank you!

**Comment by vulptex** [comment]
For `DOWNLOAD_ONLY True` packages this is still spit out:

```
Calling FetchContent_Populate(gcc-arm-none-eabi) is deprecated, call
  FetchContent_MakeAvailable(gcc-arm-none-eabi) instead.  Policy CMP0169 can
  be set to OLD to allow FetchContent_Populate(gcc-arm-none-eabi) to be
  called directly for now, but the ability to call it with declared details
  will be removed completely in a future version.
```
