### ISSUE TITLE
Question: May I only use cpm to download prebuilt libraries without configure it?

### ISSUE THREAD

**Issue by aiyolo** [cpm-cmake/CPM.cmake#601]
I have mad several prebuilt libraries, I only need to download it to third-party folder, can I use cpm to download my libraries?

**Comment by Avus-c** [comment]
You can use these arguments:
- `SOURCE_DIR` lets you specify a custom download location.
- `DOWNLOAD_ONLY` ensures CPM doesn't add it to the build.

```cmake
CPMAddPackage(
    NAME lib
    VERSION ...
    GITHUB_REPOSITORY ...
    SOURCE_DIR ./third_party
    DOWNLOAD_ONLY YES
)
```

**Comment by aiyolo** [comment]
Thanks for you reply, I will give it a try.
