### ISSUE TITLE
Running command before build

### ISSUE THREAD

**Issue by DeltaW0x** [cpm-cmake/CPM.cmake#607]
Hello! First of all, I wanted to thank everybody who works on this repo because it greatly, enormously simplyfied managing dependencies for my project. 
I have a question though, some repos I need to use (like [glslang](https://github.com/KhronosGroup/glslang)) often require to run scripts before building, mainly to fetch other dependencies. Is there any way to specify a shell command to run before compilation?

**Comment by Avus-c** [comment]
Take a look at cmake's [`execute_process`](https://cmake.org/cmake/help/latest/command/execute_process.html#execute-process) command.

After your `CPMAddPackage( glslang ...)` call, you can use this function to execute the scripts.

:)

**Comment by DeltaW0x** [comment]
Oh hey thank you, I didn't know that existed, it worked perfectly! Thank you
