### ISSUE TITLE
Question about CPM_SOURCE_CACHE

### ISSUE THREAD

**Issue by kelbon** [cpm-cmake/CPM.cmake#612]
Does it make sense to define it at start (if not defned yet) or every project to CMAKE_BINARY_DIR for recursive dependencies (which use CPM) ?

Will it reduce count of downloadings or CPM handles it itself?

**Comment by Avus-c** [comment]
It's best to define it at the start. The `CPM_SOURCE_CACHE` setting will apply to all subprojects, ensuring they share the same cache.
Dependencies will only be downloaded once, provided that the version, tags, and download location (github,...) are the same.

**Comment by kelbon** [comment]
> It's best to define it at the start (via presets, your configure command, or in your environment). The `CPM_SOURCE_CACHE` setting will apply to all subprojects, ensuring they share the same cache. Dependencies will only be downloaded once, provided that the version, tags, and download location (github,...) are the same.

Im talking about this:

```cmake
if (NOT DEFINED CPM_SOURCE_CACHE)
  set(CPM_SOURCE_CACHE ${CMAKE_BINARY_DIR})
endif()
```

Will it change anything in CPM behavior or CPM do it by default?

**Comment by Avus-c** [comment]
Ah ok.
No you don't have to define a cache.
CPM will download your deps, and subproject deps into the same folder.
